apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      name: postgres
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: postgres
            - secretRef:
                name: postgres
          image: postgres:12
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 250m
              memory: 512M
            requests:
              cpu: 50m
              memory: 256M
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      restartPolicy: Always
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres
