apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: postgres
  labels:
    app: postgres
type: kubernetes.io/basic-auth
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
