apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: postgres
  labels:
    app: postgres
spec:
  capacity:
    storage: 64G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /var/lib/postgresql/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64G
