apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
  name: traefik
  namespace: kube-public
spec:
  ports:
    - name: web
      nodePort: 30021
      port: 80
      protocol: TCP
      targetPort: 80
    - name: dashboard
      nodePort: 30042
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: traefik
  type: NodePort
