apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: default
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: redis
            - configMapRef:
                name: postgres
            - secretRef:
                name: postgres
          image: epitechcontent/t-dop-600-worker:k8s
          name: worker
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 250m
              memory: 128M
      restartPolicy: Always
